### PR TITLE
Removed unused import

### PR DESCRIPTION
**Pull request by BorzdeG**
1. Removed unused import
2. Added EditorConfig configuration

### CODE REVIEW

**Comment by andydotxyz** [comment]
I'm not sure why your editor config is part of this fix? We don't have that sort of metadata pushed in the repos.

**Comment by BorzdeG** [comment]
This is not my editor - this is for [everyone](https://editorconfig.org/). The configuration seems to correspond to what is used in the source code - indents and so on.
Removed GoLand-only settings and left general

**Comment by Jacalz** [comment]
I also don’t think we should include any configuration for the code editor. Everyone uses different settings and different editors. We should not enforce any editor settings on other developers.

**Comment by andydotxyz** [comment]
The actual fix represented here was a good one, do you not want to consider landing it without the metadata files?

**Comment by BorzdeG** [comment]
@andydotxyz I made a separate "clean" PR: https://github.com/fyne-io/gl-js/pull/11

**Comment by andydotxyz** [comment]
Thanks

**Pull request closed without merging**
