### PR TITLE
WebGL.GetError on Firefox does sometime return a string...

### PR DESCRIPTION
**Pull request by Bluebugs**

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Ouch! 
Is it possible to add a small test for this so we don't regress in the future?

**Comment by Bluebugs** [comment]
Hum, I do not have a good idea yet on how to write test for this wrapper. Will think about it a bit.

**Comment by Bluebugs** [comment]
Might be able to do something by mocking 'c'.

**Comment by andydotxyz** [comment]
I don't think it needs to be that complex. If it was a new method (`getErrorInt` or something) that passes in the result of `c.GetError` then you don't have to mock anything...

**Comment by Bluebugs** [comment]
> I don't think it needs to be that complex. If it was a new method (`getErrorInt` or something) that passes in the result of `c.GetError` then you don't have to mock anything...

This wouldn't prove that their is no regression as we could change the code that call getError and we wouldn't trigger that path. Never the less, I realize that this is a bit more complex as this code use the js.Value from syscall/js provided by go wasm. Meaning the code can only be executed inside a browser. There are solution to run wasm test in a github action using an embedded chrome, but I think this is a large scope creep on this PR. It would be good to add tests infrastructure to cover problem like this.

**Comment by andydotxyz** [comment]
> This wouldn't prove that their is no regression as we could change the code that call getError and we wouldn't trigger that path. Never the less, I realize that this is a bit more complex as this code use the js.Value from syscall/js provided by go wasm. Meaning the code can only be executed inside a browser. There are solution to run wasm test in a github action using an embedded chrome, but I think this is a large scope creep on this PR. It would be good to add tests infrastructure to cover problem like this.

Accepting as too much work at this time, this repo is a fork of other work and does not have the same standards as Fyne main.
Be aware that all new code should have tests in our main repos, eventually we will insist on the same for all as the runtime depends on quality all the way down.

**Review by andydotxyz — APPROVED** [review]
I'm not a fan of arguments to not test, but in the repo this is forked from it seems the default is not to test...

**Pull request merged**
